// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9u7ZI77qSgjWNj8GqJcpaCr0NEInAmqY',
    appId: '1:546201676053:web:4b8519d558fbaf3d38611c',
    messagingSenderId: '546201676053',
    projectId: 'notificationtest-35525',
    authDomain: 'notificationtest-35525.firebaseapp.com',
    storageBucket: 'notificationtest-35525.appspot.com',
    measurementId: 'G-RDF0B27PE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLJP4ogvADInBC2IWNrSRo-HGHFF2IPVo',
    appId: '1:546201676053:android:c3e36ea2fceb3b6638611c',
    messagingSenderId: '546201676053',
    projectId: 'notificationtest-35525',
    storageBucket: 'notificationtest-35525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC93IDTjYWvm0wRxdUbtnRge9UQDUhRfS8',
    appId: '1:546201676053:ios:8fb22db8557be23738611c',
    messagingSenderId: '546201676053',
    projectId: 'notificationtest-35525',
    storageBucket: 'notificationtest-35525.appspot.com',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC93IDTjYWvm0wRxdUbtnRge9UQDUhRfS8',
    appId: '1:546201676053:ios:2b5adfc81c67a8de38611c',
    messagingSenderId: '546201676053',
    projectId: 'notificationtest-35525',
    storageBucket: 'notificationtest-35525.appspot.com',
    iosBundleId: 'com.example.notifications.RunnerTests',
  );
}
